#! /usr/bin/env node

var path = require("path");

if (process.platform !== 'darwin') {
    console.error('TODO: Unsupported platform: ' + process.platform);
    process.exit(1);
}

var spawn = require("child_process").spawn;

new Promise(function(resolve){
    child = spawn('npm', ['root', '-g']);
    child.stdout.on('data', function(data){
        resolve(data.toString().trim());
    });
}).then(function(modules){
    cmd = path.join(modules, 'electron-prebuilt', 'dist', 'Electron.app', 'Contents', 'MacOS', "Electron");
    app = path.resolve(__dirname, '..');
    console.log("Running " + cmd + " " + app);
    child = spawn(cmd, [app]);
    child.on('close', function(exit_val){
        process.exit(exit_val);
    });
});

// vim:ft=javascript:
